config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks", }

  resources :reports
  resources :instructors
  resources :checkins
  resources :students do
    get :become
  end
  resources :cohorts, only: :show

  resources :submissions do
    patch :complete
    patch :unfinish
  end

  resources :adjustments, only: :create do
    member do
      patch :adjust
      patch :close
    end
  end

  resources :assignments, only: [:show] do
    collection do
      get :current
      get :search
    end
  end

  namespace 'staff' do
    root to: 'cohorts#show'
    resources :cohorts do
      resources :days
      resources :assignments
      resources :reports
    end
    resources :campuses
    resources :students, only: [:show, :edit, :update]
    resources :badges, except: :index
    resources :ratings, only: [:create, :update]
    resources :tags, only: :create
  end

  root to: "cohorts#my"

  get '404', :to => 'application#page_not_found'
  get '422', :to => 'application#server_error'
  get '500', :to => 'application#server_error'
end

app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :user
  belongs_to :cohort
  has_many :submissions
  has_many :assignments, -> { uniq }, through: :submissions
  has_many :complete_assignments, -> { where(submissions: { completed: true }).uniq }, through: :submissions, source: :assignment
  has_many :badges, through: :submissions
  has_many :checkins
  has_many :adjustments, through: :checkins
  accepts_nested_attributes_for :user
  validates_presence_of :cohort

  def marked_checkins
    checkins.includes(:adjustment).select { |checkin| checkin.late }
  end

  def badge_list
    @badges ||= badges.uniq
    [@badges, Badge.all - @badges]
  end

  def tardies
    checkins.select { |c| c.late }.count
  end

  def absences
    cohort.days.count - checkins.count
  end

  def completed_assignments
    submissions.where(completed: true)
  end

  def complete_percentage
    (complete_assignments.count.to_f / cohort.assignments.count.to_f).round(2)
  end

  def past_due_count
    Assignment.late_for(self).count
  end

  def name
    (user.name || user.email) if user
  end

  def to_s
    if user
      user.to_s
    else
      "StudentID#{self.id}"
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index

  def index
    students = policy_scope(Student)
    render locals: {
      students: students
    }
  end

  def show
    student = Student.find(params[:id])
    authorize student
    render locals: {
      student: student.decorate
    }
  end

  def become
    student = Student.find(params[:student_id])
    authorize student
    sign_in(student.user)
    redirect_to root_path
  end

  def edit
    student = Student.find(params[:id])
    authorize student
    render locals: {
      student: student
    }
  end

  def update
    student = Student.find(params[:id])
    authorize student
    if student.update(student_params) && student.user.update(user_params)
      redirect_to student_path(student), notice: 'Profile successfully updated'
    end
  end

  private

  def student_params
    params.require(:student).permit(:phone, :blog, :bio, :twitter)
  end

  def user_params
    params.require(:student).require(:user_attributes).permit(:name, :github, :email)
  end
end

app/views/students/_fields.html.erb
<div class='form-inputs'>
  <%= f.association :cohort, required: true %>
</div>

app/views/students/edit.html.erb
<%= link_to 'Back', url_for(:back), class: 'btn btn-primary' %>
<h1><%= student.name %></h1>

<p class='muted'>Contact Info</p>
<section>
  <%= simple_form_for(student) do |f| %>
    <div class='form-inputs'>
      <%= f.simple_fields_for :user do |u| %>
        <%= u.input :name %>
        <%= u.input :email %>
        <%= u.input :github %>
      <% end %>
      <%= f.input :blog, as: :url %>
      <%= f.input :twitter %>
      <%= f.input :phone %>
      <%= f.input :bio, as: :text %>
    </div>
    <div class='form-actions'>
      <%= f.button :submit %>
    </div>
  <% end %>
  <ul>
  </ul>
</section>

app/views/students/edit.html.slim
= link_to 'Back', url_for(:back), class: 'btn btn-primary'
h1
  = student.name
p.muted
  | Contact Info
section
  = simple_form_for(student) do |f|
    .form-inputs
      = f.input :name
      = f.input :github, hint: 'Not the full url just your profile name'
      = f.input :phone
      = f.input :twitter, hint: 'Not the full url just your profile name'
      = f.input :blog, as: :url
      = f.input :bio, as: :text
    .form-actions
      = f.button :submit
  ul

app/views/students/index.slim
table.table.table-hover
  thead
    tr
      th Email
      th Name
      th
  tbody
    - students.each do |student|
      tr
        td = student.email
        td = student.name
        td = link_to "View", student_path(student)

app/views/students/show.html.slim
.row
  .col-md-offset-3.col-md-6
    .row
      .col-md-12
        = image_tag student.avatar_url, class: 'center-block circle'
    .row
      .col-md-12
        h1.text-center
          = student.name
    .row
      .col-md-12
        = student.bio
    .row
      .col-md-8
        '  Github:
        = link_to student.github, "https://github.com/#{student.github}"
      .col-md-4
        '  Phone:
        = link_to student.phone, "tel://#{student.phone}"
    .row
      .col-md-8
        '  Twitter:
        = link_to student.twitter, "https://twitter.com/#{student.twitter}"
      .col-md-4
        '  Blog:
        = student.blog_link
    - if policy(student).edit?
      = link_to 'Edit', edit_student_path(student), class: 'btn btn-primary'
    - if policy(student).become?
      = link_to 'Become', student_become_path(student), class: 'btn btn-primary'
.row
  .col-md-6
    section
      header
        h3
          | Badges
      .row
        .col-sm-12.badges
          - student.badge_list.each_with_index do |badge_set, i|
            - badge_set.each do |badge|
              .col-md-3.col-sm-4.col-xs-6
                span class="#{'tint' unless i.zero?} circle"
                  = image_tag attachment_url(badge, :icon_image, :fill, 200, 200, format: 'png'), class: 'shadow-z-1 circle student-badge', tabindex: 0, 'data-trigger': "focus", 'data-toggle': 'popover', 'data-placement': 'bottom', 'data-title': badge.name, 'data-content': badge.description
  - if policy(student).grades?
    .col-md-6
      section
        header
          h3
            | Stats
        table.table.table-hover
          thead

          tbody
            tr
              td.align-middle
                | Tardies
              td
                h3
                  = student.tardies
            tr
              td.align-middle
                | Absences
              td
                h3
                  = student.absences
            tr
              td.align-middle
                | Completed Assignments
              td
                h3
                  = student.complete_percentage * 100
                  | %
            tr
              td.align-middle
                | Past Due Assignments
              td
                h3
                  = student.past_due_count
.row
  .col-md-12
    section
      header
        h3
          | Assignments
    table.table.table-hover
      thead
        tr
          td
            | Title
          td
            | Status
          td
            | Latest Submission
      tbody
        - student.assignments.each do |assignment|
          tr
            td
              = link_to assignment.title, assignment
            td
              = status_for(assignment, student)
            td
              - submission = assignment.submissions_for(student).last
              = link_to react_time(submission.updated_at, hoverable: false), submission