config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks", }

  resources :reports
  resources :instructors
  resources :checkins
  resources :students do
    get :become
  end
  resources :cohorts, only: :show

  resources :submissions do
    patch :complete
    patch :unfinish
  end

  resources :adjustments, only: :create do
    member do
      patch :adjust
      patch :close
    end
  end

  resources :assignments, only: [:show] do
    collection do
      get :current
      get :search
    end
  end

  namespace 'staff' do
    root to: 'cohorts#show'
    resources :cohorts do
      resources :days
      resources :assignments
      resources :reports
    end
    resources :campuses
    resources :students, only: [:show, :edit, :update]
    resources :badges, except: :index
    resources :ratings, only: [:create, :update]
    resources :tags, only: :create
  end

  root to: "cohorts#my"

  get '404', :to => 'application#page_not_found'
  get '422', :to => 'application#server_error'
  get '500', :to => 'application#server_error'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :cohort
  has_many :submissions, dependent: :destroy
  has_many :assignment_tags, dependent: :destroy
  has_many :tags, through: :assignment_tags
  validates :title, presence: true
  validates :cohort, presence: true

  def self.by_week(records)
    records.group_by { |assignment| assignment.due_date.beginning_of_week.to_date }
  end

  def self.search(query)
    where(arel_table[:title].matches("%#{query}%"))
  end

  def self.for(student)
    where(cohort_id: student.cohort_id).includes(:submissions).order(due_date: :DESC)
  end

  def self.current_for(student)
    self.for(student).not_late.first
  end

  def self.late_for(student)
    self.for(student).late - student.assignments
  end

  def self.incomplete_for(student)
    self.for(student) - Assignment.complete_for(student)
  end

  def self.complete_for(student)
    self.for(student).where(submissions: { student_id: student.id, completed: true }).uniq
  end

  def self.not_late
    where(Assignment.arel_table[:due_date].gt(Time.zone.now))
  end

  def self.late
    where(Assignment.arel_table[:due_date].lt(Time.zone.now))
  end

  def submissions_for(student)
    submissions.includes(:ratings).where(student_id: student.id).order('created_at ASC')
  end

  def completed_by?(student)
    submissions_for(student).where(completed: true).count > 0
  end

  def incomplete_by?(student)
    submissions = Arel::Table.new(:submissions)
    student_submissions = submissions_for(student)
    student_submissions.where(submissions[:state].not_eq(Submission::PENDING),
                              submissions[:completed].eq(false)
                                .or(submissions[:completed].eq(nil))).count > 0 &&
    student_submissions.where(submissions[:completed].eq(true)).count == 0
  end

  def unsubmitted_by
    self.cohort.students.where("id NOT IN (?)", self.submissions.pluck(:student_id).uniq)
  end

  def late?
    Time.zone.now > due_date
  end

  def to_s
    "Title: #{title} | Due: #{due_date}"
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

  def show
    render locals: {
      assignment: Assignment.find(params[:id])
    }
  end

  def current
    assignment = Assignment.current_for(current_user.student)
    if assignment
      redirect_to assignment_path(assignment)
    else
      redirect_to root_path, notice: 'All assignments are past due or completed.'
    end
  end

  def search
    render json: Assignment.search(params[:query])
  end

  def edit
    render locals: {
      assignment: Assignment.find(params[:id])
    }
  end
end

app/controllers/staff/application_controller.rb
class Staff::ApplicationController < ApplicationController
end

app/controllers/staff/assignments_controller.rb
class Staff::AssignmentsController < Staff::ApplicationController

  def new
    render locals: {
      assignment: Assignment.new,
      cohort: Cohort.find(params[:cohort_id]).decorate
    }
  end

  def show
    assignment = Assignment.find(params[:id])
    render locals: {
      assignment: assignment.decorate,
      submitted: assignment.submissions,
      unsubmitted: assignment.unsubmitted_by
    }
  end

  def edit
    render locals: {
      assignment: Assignment.find(params[:id]),
      cohort: Cohort.find(params[:cohort_id]).decorate
    }
  end

  def create
    cohort = Cohort.find(params[:cohort_id])
    assignment = Assignment.new(assignment_params)
    assignment.cohort   = cohort
    assignment.due_date = ActiveSupport::TimeZone[cohort.tz].parse(params[:assignment][:due_date])
    if assignment.save
      redirect_to staff_cohort_assignment_path(cohort, assignment), notice: 'Assignment successfully created'
    else
      render :new, alert: 'Assignment could not be saved', status: 422, locals: { cohort: cohort.decorate, assignment: assignment }
    end
  end

  def update
    assignment = Assignment.find(params[:id])
    params[:assignment][:due_date] = ActiveSupport::TimeZone[assignment.cohort.tz].parse(params[:assignment][:due_date])
    if assignment.update(assignment_params)
      redirect_to staff_cohort_assignment_path(assignment.cohort, assignment), notice: 'Assignment updated'
    else
      render :edit, alert: 'Assignment could not be updated', status: 422, locals: { cohort: assignment.cohort.decorate, assignment: assignment }
    end
  end

  private

  def assignment_params
    params.require(:assignment).permit(:title, :due_date, :info, tag_ids: [])
  end
end

app/controllers/staff/badges_controller.rb
class Staff::BadgesController < Staff::ApplicationController
  def new
    render locals: {
      badge: Badge.new
    }
  end

  def edit
    render template: 'badges/new', locals: {
      badge: Badge.find(params[:id])
    }
  end

  def show
    render locals: {
      badge: Badge.find(params[:id])
    }
  end

  def update
    badge = Badge.find(params[:id])
    if badge.update(badge_params)
      redirect_to staff_badge_path(badge), notice: 'Badge updated!'
    else
      render :new
    end
  end

  def create
    badge = Badge.new(badge_params)
    if badge.save
      redirect_to staff_badge_path(badge), notice: 'New badge created!'
    else
      render :new
    end
  end

  private
  def badge_params
    params.require(:badge).permit(:name, :description, :icon_image)
  end
end

app/controllers/staff/campuses_controller.rb
class Staff::CampusesController < Staff::ApplicationController
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index

  def index
    render locals: {
      campuses: policy_scope(Campus.all)
    }
  end

  def new
    campus = Campus.new
    authorize campus
    render locals: {
      campus: campus
    }
  end

  def create
    campus = Campus.new(campus_params)
    authorize campus
    if campus.save
      redirect_to staff_campuses_path, notice: I18n.t('.created', resource: I18n.t('.campus'))
    else
      render :new, locals: {campus: campus}
    end
  end

  private

  def campus_params
    params.require(:campus).permit(:name, :latitude, :longitude, :time_zone)
  end
end

app/controllers/staff/cohorts_controller.rb
class Staff::CohortsController < Staff::ApplicationController
  def new
    cohort = Cohort.new
    authorize cohort
    render locals: {
      cohort: cohort
    }
  end

  def show
    return find_cohort unless params[:id]
    @cohort      = Cohort.find(params[:id]).decorate
    authorize @cohort
    students    = @cohort.students.includes(:adjustments)
    assignments = @cohort.assignments.order('due_date DESC')
    adjustments = students.flat_map(&:adjustments)
    session[:cohort_id] = @cohort.id
    render locals: {
      cohort: @cohort.decorate,
      assignments: assignments.decorate,
      adjustments: adjustments
    }
  end

  def index
    @cohorts = CohortDecorator.decorate_collection(Cohort.all.order(:instructor_id, :created_at))
  end

  def create
    # rails does not know how to deal with multiparameter attributes on a virtual attribute
    params[:cohort][:start_date] = Date.new(params[:cohort][:"start_date(1i)"].to_i, params[:cohort][:"start_date(2i)"].to_i, params[:cohort][:"start_date(3i)"].to_i)
    params[:cohort].delete(:"start_date(1i)")
    params[:cohort].delete(:"start_date(2i)")
    params[:cohort].delete(:"start_date(3i)")
    # end terribleness
    cohort = Cohort.new(cohort_params)
    cohort.instructor_ids = [params[:cohort][:instructor_id]]
    authorize cohort
    if cohort.save
      redirect_to staff_cohort_path(cohort), notice: I18n.t('.created', resource: I18n.t('.cohort'))
    else
      render :new, locals: { cohort: cohort }
    end
  end

  private

  def cohort_params
    params.require(:cohort).permit(:name, :campus_id, :start_date, :instructor_id)
  end

  def find_cohort
    if current_user && current_user.instructor? && session[:cohort_id]
      redirect_to staff_cohort_path(session[:cohort_id])
    elsif current_user && current_user.instructor?
      redirect_to staff_cohorts_path
    end
  end
end

app/controllers/staff/days_controller.rb
class Staff::DaysController < Staff::ApplicationController
  def index
    render locals: {
      cohort: Cohort.find(params.fetch(:cohort_id)).decorate
    }
  end

  def new
    render locals: {
      cohort: Cohort.find(params[:cohort_id]).decorate,
      day: Day.new
    }
  end

  def create
    day = Day.new(day_params)
    day.cohort_id = params[:cohort_id]
    day.start = ActiveSupport::TimeZone[day.tz].parse(params[:day][:start])
    if day.save
      redirect_to staff_cohort_days_path(day.cohort), notice: I18n.t('.created', resource: I18n.t('.day'))
    else
      render :new, locals: {
        cohort: Cohort.find(params[:cohort_id]).decorate,
        day: day
      }
    end
  end

  private

  def day_params
    params.require(:day).permit(:override_code, :start)
  end
end

app/controllers/staff/reports_controller.rb
class Staff::ReportsController < Staff::ApplicationController
  before_action :set_cohort
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index

  def index
    @reports = policy_scope(Report).where(day_id: @cohort.days)
    @reports = ReportDecorator.decorate_collection(@reports)
  end

  def new
    @report = Report.new
    authorize @report
  end

  def show
    @report = Report.find(params[:id])
    authorize @report
    @report = @report.decorate
    respond_to do |format|
      format.html
      format.pdf { render pdf: "#{@report.student.name} Report", show_as_html: false}
    end
  end

  def create
    @report = Report.new(report_params)
    authorize @report
    if @report.save
      redirect_to staff_cohort_report_path(@cohort, @report), notice: I18n.t('.created', resource: I18n.t('.report'))
    else
      flash[:alert] = "Report couldn't be created because #{@report.errors.full_messages.join(', ')}"
      render :new
    end
  end

  private
  def set_cohort
    @cohort = Cohort.find(params[:cohort_id]).decorate
  end

  def report_params
    params.require(:report).permit(:student_id, :day_id, :participation, :participation_comments, :effort, :effort_comments, :skill, :skill_comments, :overall, :overall_comments, :status)
  end
end

app/views/staff/assignments/edit.html.slim
= render partial: 'staff/application/nav' , locals: { cohort: cohort }
h1 Edit Assignment
= simple_form_for([:staff, cohort, assignment]) do |f|
  .form-inputs
    = f.input :title, required: true
    = f.input :info, hint: 'put markdown in me', required: true
    = f.input :due_date, as: :string, input_html: { class: 'datetimepicker', value: assignment.due_date || (Time.zone.tomorrow + 8.hours) }, required: true
    = react_component('AssignmentTags', tags: Tag.all, tag_ids: assignment.tag_ids)
  .form-actions
    = f.button :submit

app/views/staff/assignments/new.html.slim
= render partial: 'nav', locals: {cohort: cohort}
h1 New Assignment
= simple_form_for(assignment, url: staff_cohort_assignments_path, method: :post) do |f|
  - if assignment.errors.any?
    #error_explanation
      .alert.alert-warning.flash[role="alert"]
        '  The assignment contains
        = pluralize(assignment.errors.count, "error")
        ' .
      ul
        - assignment.errors.full_messages.each do |msg|
          li = msg
  .form-inputs
    = f.input :title, required: true
    = f.input :info, hint: 'put markdown in me', required: true
    = f.input :due_date, as: :string, input_html: { class: 'datetimepicker', value: (Time.zone.tomorrow + 8.hours) }, required: true
    = react_component('AssignmentTags', tags: Tag.all, tag_ids: assignment.tag_ids)
  .form-actions
    = f.button :submit

app/views/staff/assignments/show.html.slim
.col-md-10.col-md-offset-1.col-lg-8.col-lg-offset-2
  = render partial: 'nav', locals: { cohort: assignment.cohort.decorate}
  article
    header.row
      .col-xs-12.col-sm-4
        h3 = assignment.title
      .col-xs-12.col-sm-4.pull-right
        h3
          strong
            ' Due:
          = react_time(assignment.due_date)
    .row = markdown assignment.info
    footer.row
      - if policy(Submission.new(assignment: assignment)).new?
        = link_to 'SUBMIT HOMEWORK', new_submission_path(assignment: assignment),  class:'btn btn-default btn-success'
  div
    ul.nav.nav-tabs role="tablist"
      li.active role="presentation"
        a href="#submitted" aria-controls="home" role="tab" data-toggle="tab"
          = submitted.count
          |  Submitted
      li role="presentation"
        a href="#unsubmitted" aria-controls="profile" role="tab" data-toggle="tab"
          = unsubmitted.count
          |  Unsubmitted
    .tab-content
      .tab-pane.active.fade.in role="tabpanel" id="submitted"
        - unless submitted.empty?
          ul.list
            - submitted.each do |submission|
              = link_to submission do
                li
                  = image_tag submission.student.decorate.avatar_url(64), class: 'circle user-avatar'
                  = submission.student
                  - if submission.late
                    span.pull-right.label.label-warning late
                  - if submission.unfinished?
                    span.pull-right.label.label-danger unfinished
                  - if submission.complete?
                    span.pull-right.label.label-success complete
        - else
          p No submissions
      .tab-pane.active.fade role="tabpanel" id="unsubmitted"
        - unless unsubmitted.empty?
          ul.list
            - unsubmitted.order(:last_active_at).each do |student|
              - student = student.decorate
              = link_to student do
                li
                  = image_tag student.avatar_url(64), class: 'circle user-avatar'
                  = student.info
        - else
          Everyone submitted