config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', omniauth_callbacks: "users/omniauth_callbacks", }

  resources :reports
  resources :instructors
  resources :checkins
  resources :students do
    get :become
  end
  resources :cohorts, only: :show

  resources :submissions do
    patch :complete
    patch :unfinish
  end

  resources :adjustments, only: :create do
    member do
      patch :adjust
      patch :close
    end
  end

  resources :assignments, only: [:show] do
    collection do
      get :current
      get :search
    end
  end

  namespace 'staff' do
    root to: 'cohorts#show'
    resources :cohorts do
      resources :days
      resources :assignments
      resources :reports
    end
    resources :campuses
    resources :students, only: [:show, :edit, :update]
    resources :badges, except: :index
    resources :ratings, only: [:create, :update]
    resources :tags, only: :create
  end

  root to: "cohorts#my"

  get '404', :to => 'application#page_not_found'
  get '422', :to => 'application#server_error'
  get '500', :to => 'application#server_error'
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :student
  belongs_to :day
  validates :day, :student, presence: true

  enum status: {
    "Satisfactory"    => 0,
    "Unsatisfactory"  => 1,
    "Probation"       => 2
  }

  def cohort
    day.cohort
  end

  def end_of_day
    day.start.end_of_day
  end

  def completed_assignments
    Assignment.complete_for(student).where("due_date <= ?", end_of_day)
  end

  def assignments
    Assignment.for(student).where("due_date <= ?", end_of_day)
  end

  def attended
    student.checkins.where("created_at <= ?", end_of_day)
  end

  def tardies
    student.checkins.where("created_at <= ?", end_of_day).select{|c| c.late?}
  end

  def lectures
    cohort.days.where("start <= ?", end_of_day)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index

  def index
    authorize Report
    @reports = policy_scope(Report)
  end

  def new
    @report = Report.new
    authorize @report
    @students = current_user.instructor.current_cohort.students
  end

  def show
    @report = Report.find(params[:id]).decorate
    authorize @report
    respond_to do |format|
      format.html
      format.pdf { render pdf: "#{@report.student.name} Report", show_as_html: false}
    end
  end
end

app/controllers/staff/reports_controller.rb
class Staff::ReportsController < Staff::ApplicationController
  before_action :set_cohort
  after_action :verify_authorized, :except => :index
  after_action :verify_policy_scoped, :only => :index

  def index
    @reports = policy_scope(Report).where(day_id: @cohort.days)
    @reports = ReportDecorator.decorate_collection(@reports)
  end

  def new
    @report = Report.new
    authorize @report
  end

  def show
    @report = Report.find(params[:id])
    authorize @report
    @report = @report.decorate
    respond_to do |format|
      format.html
      format.pdf { render pdf: "#{@report.student.name} Report", show_as_html: false}
    end
  end

  def create
    @report = Report.new(report_params)
    authorize @report
    if @report.save
      redirect_to staff_cohort_report_path(@cohort, @report), notice: I18n.t('.created', resource: I18n.t('.report'))
    else
      flash[:alert] = "Report couldn't be created because #{@report.errors.full_messages.join(', ')}"
      render :new
    end
  end

  private
  def set_cohort
    @cohort = Cohort.find(params[:cohort_id]).decorate
  end

  def report_params
    params.require(:report).permit(:student_id, :day_id, :participation, :participation_comments, :effort, :effort_comments, :skill, :skill_comments, :overall, :overall_comments, :status)
  end
end

app/views/reports/index.slim
table.table.table-hover
  thead
    tr
      - if current_user.instructor?
        th Student Name
      th Day
      th Status
  tbody
    - @reports.each do |report|
      tr
        - if current_user.instructor?
          td = report.student.name
        td = report.day
        td = report.status
        td = link_to "View", report

- if policy(Report).create?
  = link_to "Create Report", new_report_path, class: 'btn btn-primary'

app/views/reports/show.html.slim
= link_to "Download PDF", { format: :pdf }, class: 'btn btn-primary'
.row
  .col-xs-4
    .logo-box.clearfix
      = image_tag 'iron-yard-logo.svg', style: 'float: right;'
    h4.text-right
      | Campus
    p.text-right
      = @report.campus_name
    h4.text-right
      | Course
    p.text-right
      = @report.cohort_name
    h4.text-right
      | Instructor
    p.text-right
      = @report.instructor_name
    h4.text-right
      | Student
    p.text-right
      = @report.student_name
  .col-xs-8
    h1
      | Bi-Weekly Performance
    p.description
      | TIY students will be assessed every two weeks during the regular session, and every week during the final project (unless otherwise noted by the Instructor. On a biweekly basis, students will be assessed on their participation, effort, and skill on a Likert scale from 1 (unsatisfactory) to 3 (satisfactory) with room for comments. In addition, students’ overall performance and accountability will be assessed, including attendance and meeting homework and career assistance deadlines.
    h2
      | Participation (
      = @report.participation
      | )
    p
      | Comments:
    = content_tag(:p, @report.participation_comments)
    h2
      | Effort (
      = @report.effort
      | )
    p
      | Comments:
    = content_tag(:p, @report.effort_comments)
    h2
      | Skill (
      = @report.skill
      | )
    p
      | Comments:
    = content_tag(:p, @report.skill_comments)
    h2
      | Overall Performance (
      = @report.overall
      | )
    h4
      | Attendance:
    p
      ' Student has attended
      = @report.attended
      '  out of
      = @report.total_lectures
      '  lectures, being late for
      = @report.tardies
      |  attended lecture(s).
    h4
      | Completed assignments:
    p
      ' Student has completed
      = @report.completed_assignments
      '  of
      = @report.total_assignments
      |  assignments in total during the 12-week session.
    h4
      | Comments:
    = content_tag(:p, @report.overall_comments)
    h3 = @report.status
    p.description
      strong
        | Satisfactory:
      |  Meeting course standards and requirements; continues receiving career support and ability to present at Demo Day.
    p.description
      strong
        | Unsatisfactory:
      |  Not meeting course standards and requirements, must improve performance before next review and maintain performance in order to receive both career support and ability to present at Demo Day.
    p.description
      strong
        | Probation:
      |  Continued failure to meet course standards and requirements; access to career support and ability to present at Demo Day are temporarily revoked until the end of semester (or other time as specified by staff) at which time a review of progress takes place.If the results are satisfactory, career support and ability to present at Demo Day will be reinstated.